#sudo é necessário sempre que utilizamos o docker
sudo: required
#Indica que precisamos que o docker esteja instalado
services:
  - docker
#Acontece antes do deploy ou antes de rodar os testes
#indica que precisa criar a imagem
before_install:
  - docker build -t jayce/docker-react -f Dockerfile.dev .  

script:
  -  docker run jayce/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "sa-east-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-sa-east-1-412119120494"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRETY_KEY"

  