#sudo é necessário sempre que utilizamos o docker
sudo: required
#Indica que precisamos que o docker esteja instalado
services:
  - docker
#Acontece antes do deploy ou antes de rodar os testes
#indica que precisa criar a imagem
before_install:
  - docker build -t jayce/docker-react -f Dockerfile.dev .  

script:
  -  docker run jayce/docker-react npm run test -- --coverage